### ISSUE TITLE
Seção de Histórico

### ISSUE THREAD

**Issue by LeviUSP** [MatKurianski/project-ceres-front#1]
Mais um ponto de deixar últimas compras

As 5 últimas é um número bacana

**Comment by MatKurianski** [comment]
Fiz um pequeno teste. Não sei se conseguirei facilmente colocar 5 sem perda de reusabilidade dos componentes, mas pelo menos até quarta já temos isso

![Screenshot_20191021-151153](https://user-images.githubusercontent.com/38268201/67231225-46279300-f415-11e9-839d-415b11569126.jpg)

**Comment by LeviUSP** [comment]
Perfeito!
5 foi um chute inicial. Acho que, dessa forma, pode ser apenas 3 msm
