### ISSUE TITLE
Barra de nome e busca fixa

### ISSUE THREAD

**Issue by LeviUSP** [MatKurianski/project-ceres-front#2]
Assim como no iFood, temos que deixar essa barra fixa quando dar scroll.

![WhatsApp Image 2019-10-21 at 12 11 33 PM](https://user-images.githubusercontent.com/39068012/67217989-043e2300-f3fc-11e9-84de-459b10d83430.jpeg)

![WhatsApp Image 2019-10-21 at 12 11 33 PM (1)](https://user-images.githubusercontent.com/39068012/67218013-0acc9a80-f3fc-11e9-9651-7c600cfd6a0b.jpeg)

**Comment by MatKurianski** [comment]
Eu tava pesquisando justamente sobre isso ontem à noite. Não encontrei uma solução que me satisfez então em breve estudarei a Animated API do React para tentar simular o efeito.
